# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f8643df7da36216bb00b95de3f27102bd6d658f7be25242832b74b771101490c97288ec29993fe1620bc6c4ef0cb1405c5b9ff7104469cf54b4fc45094b9df1c

test:
  secret_key_base: 50a056d151b3de790db89f7aad5318c68941cb1635b904d36aa73d3036935c1cc1d073a6d10c38003d08e6614fff2e1ca78a745c8531b380e7595317817be638

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
